# Generated by Django 2.0.7 on 2018-07-16 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocate', '0002_auto_20180716_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='chore',
            name='fixedValue',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
