# Generated by Django 2.0.7 on 2018-07-25 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allocate', '0003_chore_fixedvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocation',
            name='score',
            field=models.FloatField(default=100),
        ),
        migrations.AlterField(
            model_name='chore',
            name='household',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allocate.Household'),
        ),
        migrations.AlterField(
            model_name='doer',
            name='household',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allocate.Household'),
        ),
        migrations.AlterField(
            model_name='weight',
            name='chore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allocate.Chore'),
        ),
    ]
