# Generated by Django 2.0.7 on 2018-07-25 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allocate', '0004_auto_20180725_1126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allocation',
            options={'ordering': ['household', 'score']},
        ),
    ]
