# Generated by Django 2.0.7 on 2018-07-25 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allocate', '0005_auto_20180725_1156'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weight',
            options={'ordering': ['chore', 'doer']},
        ),
    ]
