# Generated by Django 2.0.7 on 2018-07-25 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allocate', '0007_auto_20180725_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chore',
            name='doer',
            field=models.ForeignKey(blank=True, limit_choices_to={'household': models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allocate.Household')}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='allocate.Doer'),
        ),
    ]
