# Generated by Django 2.0.7 on 2018-07-25 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allocate', '0008_auto_20180725_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='household',
            name='allocations_are_current',
        ),
        migrations.AddField(
            model_name='household',
            name='editing',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='chore',
            name='doer',
            field=models.ForeignKey(blank=True, help_text='If fixed, who has to do this chore?', null=True, on_delete=django.db.models.deletion.SET_NULL, to='allocate.Doer', verbose_name='Assigned to'),
        ),
        migrations.AlterField(
            model_name='chore',
            name='fixedValue',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='If fixed, mutually agreed upon value of chore (out of 100)', max_digits=8, null=True, verbose_name='Assigned value'),
        ),
        migrations.AlterField(
            model_name='chore',
            name='isFixed',
            field=models.BooleanField(default=False, help_text='Does this chore have to be done by a particular person?', verbose_name='Assigned?'),
        ),
        migrations.AlterField(
            model_name='chore',
            name='name',
            field=models.CharField(help_text='Enter the name of a chore', max_length=40, verbose_name='Chore name'),
        ),
        migrations.AlterField(
            model_name='household',
            name='name',
            field=models.CharField(help_text="Enter a name for the household (e.g., 'The Scotts')", max_length=40, unique=True),
        ),
    ]
