# Generated by Django 2.0.7 on 2018-07-27 15:01

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('allocate', '0009_auto_20180725_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocation',
            name='doerScores',
            field=jsonfield.fields.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='chore',
            name='doer',
            field=models.ForeignKey(blank=True, help_text='If assigned, who has to do this chore?', null=True, on_delete=django.db.models.deletion.SET_NULL, to='allocate.Doer', verbose_name='Assigned to'),
        ),
        migrations.AlterField(
            model_name='chore',
            name='fixedValue',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='If assigned, mutually chosen value of chore (out of 100)', max_digits=8, null=True, verbose_name='Assigned value'),
        ),
    ]
