# Generated by Django 2.0.7 on 2018-07-27 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allocate', '0010_auto_20180727_1101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allocation',
            old_name='doerScores',
            new_name='allScores',
        ),
    ]
