# Generated by Django 2.0.7 on 2018-07-30 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocate', '0011_auto_20180727_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='haveAllocations',
            field=models.IntegerField(default=0),
        ),
    ]
