# Generated by Django 2.0.7 on 2018-07-30 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocate', '0012_auto_20180730_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='doingAllocations',
            field=models.BooleanField(default=False),
        ),
    ]
